### PR TITLE
Last stable version before adding thrift/protobuf RPC

### PR DESCRIPTION
**Pull request by mcfatealan**
HTML `table` has strict element type limits in it. Previously I use `<template>` to repeat table blocks, however on IE/Edge it will be rendered differently from what Chrome does. Now I use an alternative, using `<tbody>` as block elements.  

> Note that unlike the <thead>, <tfoot>, and <caption> elements however, multiple <tbody> elements are permitted (if consecutive), allowing the data-rows in long tables to be divided into different sections, each separately formatted as needed. [source](https://developer.mozilla.org/de/docs/Web/HTML/Element/tbody)

### CODE REVIEW

**Comment by mcfatealan** [comment]
@imzhenyu now IE/Edge should work well. Tested.

**Comment by mcfatealan** [comment]
This PR mainly did these things:
1. Renamed monitor to `Web Studio`.
2. Refactored all main web page under `Vue.js` framework.
3. Improved python codes and directory structure.
4. Fixed a few bugs and add more useful functions.

**Comment by mcfatealan** [comment]
@imzhenyu please help review

**Comment by imzhenyu** [comment]
Great job! @mcfatealan

**Pull request merged**
